In [1]:
# We will do the imports required for this notebook here

# numpy provides import array and linear algebra utilities
import numpy as np

# the robotics toolbox provides robotics specific functionality
import roboticstoolbox as rtb

# spatial math provides objects for representing transformations
import spatialmath as sm

In [2]:
# This is a variable rotation around the x-axis
rx_var = rtb.ET.Rx()

# This is a constant rotation around the x-axis by 90 degrees
rx_cons = rtb.ET.Rx(np.pi / 2)

# By printing each of the ET's we made, we can view them in a more readable format
print(rx_var)
print(rx_cons)

Rx(q)
Rx(90°)


In [3]:
# We can calculate the transform resulting from the rx_cons ET using the .A method
transform = rx_cons.A()

# The .A method returns a numpy array
# Using the spatialmath package, we can create an SE3 object from the array
sm_transform = sm.SE3(transform)

# The spatialmath package provides great utility for working with transforms 
# and will print SE3s in a more intuitive way a plain numpy array

print(f"Numpy array SE3: \n{transform}")
print()
print(f"Spatialmath SE3: \n{sm_transform}")

Numpy array SE3: 
[[ 1.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00]
 [ 0.000000e+00  6.123234e-17 -1.000000e+00  0.000000e+00]
 [ 0.000000e+00  1.000000e+00  6.123234e-17  0.000000e+00]
 [ 0.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00]]

Spatialmath SE3: 
   1         0         0         0         
   0         0        -1         0         
   0         1         0         0         
   0         0         0         1         



In [4]:
# To calculate the transform resulting from the rx_var ET, 
# we must supply a joint coordinate when using the .A method

# Make the joint at 45 degrees
q = np.pi / 4
transform = rx_var.A(q)
sm_transform = sm.SE3(transform)
print(f"Resulting SE3 at 45 degrees: \n{sm_transform}")

Resulting SE3 at 45 degrees: 
   1         0         0         0         
   0         0.7071   -0.7071    0         
   0         0.7071    0.7071    0         
   0         0         0         1         



In [5]:
# We can also create prismatic joints
# This is a variable translation around the y-axis
ty_var = rtb.ET.ty()

# This is a constant translation along the y-axis by 25 cm
ty_cons = rtb.ET.ty(0.25)

# View the ETs
print(ty_var)
print(ty_cons)

ty(q)
ty(0.25)


In [6]:
# We can calculate the transform resulting from the ty_cons ET using the .A method
transform = ty_cons.A()

# Create an SE3 object from the array
sm_transform = sm.SE3(transform)

print(f"SE3: \n{sm_transform}")

SE3: 
   1         0         0         0         
   0         1         0         0.25      
   0         0         1         0         
   0         0         0         1         



In [7]:
# To calculate the transform resulting from the ty_var ET, 
# we must supply a joint coordinate when using the .A method

# Make the joint at 15 cm
q = 0.15
transform = ty_var.A(q)
sm_transform = sm.SE3(transform)
print(f"Resulting SE3 at 15 cm: \n{sm_transform}")

Resulting SE3 at 15 cm: 
   1         0         0         0         
   0         1         0         0.15      
   0         0         1         0         
   0         0         0         1         



In [8]:
# Note for for E7 and E11 in the figure above and code below, we use flip=True
# as the variable rotation is in the negative direction.

E1 = rtb.ET.tz(0.333)
E2 = rtb.ET.Rz()
E3 = rtb.ET.Ry()
E4 = rtb.ET.tz(0.316)
E5 = rtb.ET.Rz()
E6 = rtb.ET.tx(0.0825)
E7 = rtb.ET.Ry(flip=True)
E8 = rtb.ET.tx(-0.0825)
E9 = rtb.ET.tz(0.384)
E10 = rtb.ET.Rz()
E11 = rtb.ET.Ry(flip=True)
E12 = rtb.ET.tx(0.088)
E13 = rtb.ET.Rx(np.pi)
E14 = rtb.ET.tz(0.107)
E15 = rtb.ET.Rz()

# We can create and ETS in a number of ways

# Firstly if we use the * operator between two or more ETs, we get an ETS
ets1 = E1 * E2 * E3

# Secondly, we can use the ETS constructor and pass in a list of ETs
ets2 = rtb.ETS([E1, E2, E3])

# We can also use the * operator between ETS' and ETs to concatenate
ets3 = ets2 * E4
ets4 = ets2 * rtb.ETS([E4, E5])

print(ets1)
print(ets2)
print(ets3)
print(ets4)


tz(0.333) ⊕ Rz(q0) ⊕ Ry(q1)
tz(0.333) ⊕ Rz(q0) ⊕ Ry(q1)
tz(0.333) ⊕ Rz(q0) ⊕ Ry(q1) ⊕ tz(0.316)
tz(0.333) ⊕ Rz(q0) ⊕ Ry(q1) ⊕ tz(0.316) ⊕ Rz(q0)


In [9]:
# We can make an ETS representing a Panda by incorprating all 15 ETs into an ETS
panda = E1 * E2 * E3 * E4 * E5 * E6 * E7 * E8 * E9 * E10 * E11 * E12 * E13 * E14 * E15

# View the ETS
print(panda)
print()

# The ETS class has many usefull properties
# print the number of joints in the panda model
print(f"The panda has {panda.n} joints")

# print the number of ETs in the panda model
print(f"The panda has {panda.m} ETs")

# We can access an ET from an ETS as if the ETS were a Python list
print(f"The second ET in the ETS is {panda[1]}")

# When a variable ET is added to an ETS, it is assigned a jindex, which is short for joint index
# When given an array of joint coordinates (i.e. joint angles), the ETS will use the jindices of each
# variable ET to correspond with elements of the given joint coordiante array
print(f"The first variable joint has a jindex of {panda[1].jindex}, while the second has a jindex of {panda[2].jindex}")

# We can extract all of the variable ETs from the panda model as a list
print(f"\nAll variable liks in the Panda ETS: \n{panda.joints()}")

tz(0.333) ⊕ Rz(q0) ⊕ Ry(q1) ⊕ tz(0.316) ⊕ Rz(q2) ⊕ tx(0.0825) ⊕ Ry(-q3) ⊕ tx(-0.0825) ⊕ tz(0.384) ⊕ Rz(q4) ⊕ Ry(-q5) ⊕ tx(0.088) ⊕ Rx(180°) ⊕ tz(0.107) ⊕ Rz(q6)

The panda has 7 joints
The panda has 15 ETs
The second ET in the ETS is Rz(q0)
The first variable joint has a jindex of 0, while the second has a jindex of 1

All variable liks in the Panda ETS: 
[ET.Rz(jindex=0), ET.Ry(jindex=1), ET.Rz(jindex=2), ET.Ry(jindex=3, flip=True), ET.Rz(jindex=4), ET.Ry(jindex=5, flip=True), ET.Rz(jindex=6)]


In [10]:
# Using the above methodolgy, we can calculate the forward kinematics of our Panda model
# First, we must define the joint coordinates q, to calculate the forward kinematics at
q = np.array([0, -0.3, 0, -2.2, 0, 2, 0.79])

# Allocate the resulting forward kinematics array
fk = np.eye(4)

# Now we must loop over the ETs in the Panda
for et in panda:
    if et.isjoint:
        # This ET is a variable joint
        # Use the q array to specify the joint angle for the variable ET
        fk = fk @ et.A(q[et.jindex])
    else:
        # This ET is static
        fk = fk @ et.A()

# Pretty print our resulting forward kinematics using an SE3 object
print(sm.SE3(fk))

   0.7003   -0.7068    0.09983   0.4737    
  -0.7104   -0.7038    0         0         
   0.07027  -0.07092  -0.995     0.5155    
   0         0         0         1         



In [11]:
# The ETS class has the .fkine method which can calculate the forward kinematics
# The .fkine methods returns an SE3 object
print(f"The fkine method: \n{panda.fkine(q)}")

# The .eval method also calculates the forward kinematics but returns an numpy array
# instead of an SE3 object (use this if speed is a priority)
print(f"The eval method: \n{panda.eval(q)}")

The fkine method: 
   0.7003   -0.7068    0.09983   0.4737    
  -0.7104   -0.7038    0         0         
   0.07027  -0.07092  -0.995     0.5155    
   0         0         0         1         

The eval method: 
[[ 7.00329021e-01 -7.06804465e-01  9.98334166e-02  4.73724040e-01]
 [-7.10353272e-01 -7.03845316e-01 -1.22464680e-16 -1.31037208e-17]
 [ 7.02672827e-02 -7.09169942e-02 -9.95004165e-01  5.15513206e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [12]:
# We will do the imports required for this notebook here

# numpy provides import array and linear algebra utilities
import numpy as np

# the robotics toolbox provides robotics specific functionality
import roboticstoolbox as rtb

# spatial math provides objects for representing transformations
import spatialmath as sm
import spatialmath.base as smb

# use timeit to benchmark some methods
from timeit import default_timer as timer

# ansitable is a great package for printing tables in a terminal
from ansitable import ANSITable

In [13]:

# We can program these in Python
# These methods assume the inputs are correctly sized and numpy arrays

def vex(mat):
    '''
    Converts a 3x3 skew symmetric matric to a 3 vector
    '''

    return np.array([mat[2, 1], mat[0, 2], mat[1, 0]])

def skew(vec):
    '''
    Converts a 3 vector to a 3x3 skew symmetric matrix
    '''

    return np.array([
        [0, -vec[2], vec[1]],
        [vec[2], 0, -vec[0]],
        [-vec[1], vec[0], 0]
    ])


def vexa(mat):
    '''
    Converts a 4x4 augmented skew symmetric matric to a 6 vector
    '''

    return np.array([mat[0, 3], mat[1, 3], mat[2, 3], mat[2, 1], mat[0, 2], mat[1, 0]])

def skewa(vec):
    '''
    Converts a 6 vector to a 4x4 augmented skew symmetric matrix
    '''

    return np.array([
        [0, -vec[5], vec[4], vec[0]],
        [vec[5], 0, -vec[3], vec[1]],
        [-vec[4], vec[3], 0, vec[2]],
        [0, 0, 0, 0]
    ])


In [14]:
# Test our skew and vex methods out

x = np.array([1, 2, 3])

sk_x = skew(x)

print(f"x: \n{x}")
print(f"skew form of x: \n{sk_x}")
print(f"Perform vex operation on that, we should get the original a vector back: \n{vex(sk_x)}")

x: 
[1 2 3]
skew form of x: 
[[ 0 -3  2]
 [ 3  0 -1]
 [-2  1  0]]
Perform vex operation on that, we should get the original a vector back: 
[1 2 3]


In [15]:
y = np.array([1, 2, 3, 4, 5, 6])

ska_y = skewa(y)

print(f"y: \n{y}")
print(f"augmented skew form of y: \n{ska_y}")
print(f"Perform vexa operation on that, we should get the original y vector back: \n{vexa(ska_y)}")

y: 
[1 2 3 4 5 6]
augmented skew form of y: 
[[ 0 -6  5  1]
 [ 6  0 -4  2]
 [-5  4  0  3]
 [ 0  0  0  0]]
Perform vexa operation on that, we should get the original y vector back: 
[1 2 3 4 5 6]


In [16]:
def ρ(tf):
    '''
    The method extracts the rotational component from an SE3
    '''
    return tf[:3, :3]

def τ(tf):
    '''
    The method extracts the translation component from an SE3
    '''
    return tf[:3, 3]

In [19]:
# We can make Python functions which perform these derivatives

def dTRx(θ, flip):
    '''
    Calculates the derivative of an SE3 which is a pure rotation around
    the x-axis by amount θ
    '''
    # This is the [Rhat_x] matrix in the maths above
    Rhx = np.array([
        [0, 0, 0, 0],
        [0, 0, -1, 0],
        [0, 1, 0, 0],
        [0, 0, 0, 0]
    ])

    # This is the T_R_x matrix in the maths above
    Trx = smb.trotx(θ)

    if flip:
        return Rhx.T @ Trx.T
    else:
        return Rhx @ Trx

def dTRy(θ, flip):
    '''
    Calculates the derivative of an SE3 which is a pure rotation around
    the y-axis by amount θ
    '''
    # This is the [Rhat_y] matrix in the maths above
    Rhy = np.array([
        [0, 0, 1, 0],
        [0, 0, 0, 0],
        [-1, 0, 0, 0],
        [0, 0, 0, 0]
    ])

    # This is the T_R_y matrix in the maths above
    Try = smb.troty(θ)

    if flip:
        return Rhy.T @ Try.T
    else:
        return Rhy @ Try

def dTRz(θ, flip):
    '''
    Calculates the derivative of an SE3 which is a pure rotation around
    the z-axis by amount θ
    '''
    # This is the [Rhat_z] matrix in the maths above
    Rhz = np.array([
        [0, -1, 0, 0],
        [1, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]
    ])

    # This is the T_R_z matrix in the maths above
    Trz = smb.trotz(θ)

    if flip:
        return Rhz.T @ Trz.T
    else:
        return Rhz @ Trz

# We can make Python functions which perform these derivatives
# Since these are constant, we don't need to handle joints being
# flipped like we do with revolute joints

def dTtx():
    '''
    Calculates the derivative of an SE3 which is a pure translation along
    the x-axis by amount d
    '''
    # This is the [That_x] matrix in the maths above
    Thx = np.array([
        [0, 0, 0, 1],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]
    ])

    return Thx

def dTty():
    '''
    Calculates the derivative of an SE3 which is a pure translation along
    the y-axis by amount d
    '''
    # This is the [That_y] matrix in the maths above
    Thy = np.array([
        [0, 0, 0, 0],
        [0, 0, 0, 1],
        [0, 0, 0, 0],
        [0, 0, 0, 0]
    ])

    return Thy

def dTtz():
    '''
    Calculates the derivative of an SE3 which is a pure translation along
    the z-axis by amount d
    '''
    # This is the [That_z] matrix in the maths above
    Thz = np.array([
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 1],
        [0, 0, 0, 0]
    ])

    return Thz

In [18]:
# Before going any further, lets remake the panda model we made in the first notebook
E1 = rtb.ET.tz(0.333) 
E2 = rtb.ET.Rz()
E3 = rtb.ET.Ry() 
E4 = rtb.ET.tz(0.316) 
E5 = rtb.ET.Rz()
E6 = rtb.ET.tx(0.0825) 
E7 = rtb.ET.Ry(flip=True) 
E8 = rtb.ET.tx(-0.0825) 
E9 = rtb.ET.tz(0.384) 
E10 = rtb.ET.Rz()
E11 = rtb.ET.Ry(flip=True)
E12 = rtb.ET.tx(0.088) 
E13 = rtb.ET.Rx(np.pi / 2) 
E14 = rtb.ET.tz(0.107)
E15 = rtb.ET.Rz()
panda = E1 * E2 * E3 * E4 * E5 * E6 * E7 * E8 * E9 * E10 * E11 * E12 * E13 * E14 * E15

# And make a joint coordinate array q
q = np.array([0, -0.3, 0, -2.2, 0, 2, 0.79])

In [20]:

def dET(et, η):
    '''
    This method takes an ET and returns the derivative with respect to the joint coordinate
    This is here for convenience
    '''

    if et.axis == 'Rx':
        return dTRx(η, et.isflip)
    elif et.axis == 'Ry':
        return dTRy(η, et.isflip)
    elif et.axis == 'Rz':
        return dTRz(η, et.isflip)
    elif et.axis == 'tx':
        return dTtx()
    elif et.axis == 'ty':
        return dTty()
    else:
        return dTtz()

In [21]:
def dT_j(ets, j, q):
    '''
    This methods calculates the dervative of an SE3 with respect to joint coordinate j
    '''

    # Allocate an identity matrix for the result
    dT = np.eye(4)

    # Find the jth variable et in the ets
    et_j = ets.joints()[j]

    # Loop overs the ETs in the robot ETS
    for et in ets:
        if et == et_j:
            # This ET is variable and corresponds to joint j
            dT = dT @ dET(et, q[et.jindex])
        elif et.isjoint:
            # This ET is a variable joint
            # Use the q array to specify the joint angle for the variable ET
            dT = dT @ et.A(q[et.jindex])
        else:
            # This ET is static
            dT = dT @ et.A()

    return dT

In [25]:
def Jω_j(ets, j, q):
    '''
    This method calculates the rotational component of the jth column of the manipulator Jacobian
    '''

    # Calculate the forward kinematics at q
    T = ets.eval(q)

    # Calculate the derivative of T with respect to q_j
    dT = dT_j(ets, j, q)

    Jω = vex(ρ(dT) @ (ρ(T).T))

    return Jω

# Calculate the angular component of the third column of Panda manipulator Jacobian
print(Jω_j(panda, 2, q))

def Jv_j(ets, j, q):
    '''
    This method calculates the tranlation component of the jth column of the manipulator Jacobian
    '''

    # Calculate the derivative of T with respect to q_j
    dT = dT_j(ets, j, q)

    Jv = τ(dT)

    return Jv
    
# Calculate the translational component of the third column of Panda manipulator Jacobian
print(Jv_j(panda, 3, q))

[-2.95520207e-01 -1.23259516e-32  9.55336489e-01]
[0.0372881  0.         0.47761099]


In [26]:
# By using our previously defined methods, we can now calculate the manipulator Jacobian

def jacob0(ets, q):
    '''
    This method calculates the manipulator Jacobian in the world frame
    '''

    # Allocate array for the Jacobian
    # It is a 6xn matrix
    J = np.zeros((6, ets.n))

    for j in range(ets.n):
        Jv = Jv_j(ets, j, q)
        Jω = Jω_j(ets, j, q)

        J[:3, j] = Jv
        J[3:, j] = Jω

    return J

# Calculate the manipulator Jacobian of the Panda in the world frame
J = jacob0(panda, q)

print(f"The manipulator Jacobian (world-frame) \nin configuration q = {q} \nis: \n{np.round(J, 2)}")

The manipulator Jacobian (world-frame) 
in configuration q = [ 0.   -0.3   0.   -2.2   0.    2.    0.79] 
is: 
[[ 0.11  0.29  0.1   0.04 -0.03 -0.01  0.  ]
 [ 0.46  0.    0.53  0.   -0.04  0.    0.  ]
 [ 0.   -0.46  0.03  0.48 -0.1   0.09  0.  ]
 [ 0.    0.   -0.3   0.    0.95  0.   -0.  ]
 [ 0.    1.   -0.   -1.    0.   -1.   -1.  ]
 [ 1.    0.    0.96  0.   -0.32  0.    0.  ]]


In [28]:
# Now making the efficient version in Python

def jacob0_efficient(ets, q):
    '''
    This method calculates the manipulator Jacobian in the world frame using a more efficient method
    '''
    T = ets.eval(q)

    U = np.eye(4)
    j = 0
    J = np.zeros((6, ets.n))

    for ets in ets:
        jindex = ets.jindex

        if ets.isjoint:
            U = U @ ets.A(q[jindex])  # type: ignore

            Tu = sm.SE3(U, check=False).inv().A @ T
            n = U[:3, 0]
            o = U[:3, 1]
            a = U[:3, 2]
            x = Tu[0, 3]
            y = Tu[1, 3]
            z = Tu[2, 3]

            if ets.isflip:
                sign = -1.0
            else:
                sign = 1.0

            if ets.axis == "Rz":
                J[:3, j] = sign * ((o * x) - (n * y))
                J[3:, j] = sign * a

            elif ets.axis == "Ry":
                J[:3, j] = sign * ((n * z) - (a * x))
                J[3:, j] = sign * o

            elif ets.axis == "Rx":
                J[:3, j] = sign * ((a * y) - (o * z))
                J[3:, j] = sign * n

            elif ets.axis == "tx":
                J[:3, j] = n
                J[3:, j] = np.array([0, 0, 0])

            elif ets.axis == "ty":
                J[:3, j] = o
                J[3:, j] = np.array([0, 0, 0])

            elif ets.axis == "tz":
                J[:3, j] = a
                J[3:, j] = np.array([0, 0, 0])

            j += 1
        else:
            U = U @ ets.A()

    return J
    
J = jacob0_efficient(panda, q)

print(f"The manipulator Jacobian (world-frame) \nin configuration q = {q} \nis: \n{np.round(J, 2)}")

The manipulator Jacobian (world-frame) 
in configuration q = [ 0.   -0.3   0.   -2.2   0.    2.    0.79] 
is: 
[[ 0.11  0.29  0.1   0.04 -0.03 -0.01 -0.  ]
 [ 0.46  0.    0.53 -0.   -0.04 -0.    0.  ]
 [ 0.   -0.46  0.03  0.48 -0.1   0.09  0.  ]
 [ 0.    0.   -0.3  -0.    0.95 -0.   -0.  ]
 [ 0.    1.    0.   -1.    0.   -1.   -1.  ]
 [ 1.    0.    0.96 -0.   -0.32 -0.    0.  ]]


In [29]:
# Now making it in Python

def jacobe(ets, q):
    '''
    This method calculates the manipulator Jacobian in the end-effector frame
    '''

    # Calculate world-frame Jacobian
    J0 = jacob0_efficient(ets, q)

    # Calculate the forward kineamtics
    T = ets.eval(q)

    # Extract rotation from T and transpose
    R = T[:3, :3].T

    # Make our velocity transform matrix
    tr = np.zeros((6, 6))

    # Put the rotation in the top left and bottom right of the matrix
    tr[:3, :3] = R
    tr[3:, 3:] = R

    # Perform the matrix multiplication to calculate the Jacobian
    # in the end-effector frame
    Je = tr @ J0

    return Je

# Calculate the manipulator Jacobian of the Panda in the end-effector frame
J = jacobe(panda, q)

print(f"The manipulator Jacobian (end-effector) \nin configuration q = {q} \nis: \n{np.round(J, 2)}")

The manipulator Jacobian (end-effector) 
in configuration q = [ 0.   -0.3   0.   -2.2   0.    2.    0.79] 
is: 
[[ 0.07 -0.18  0.09  0.39 -0.1   0.06  0.  ]
 [-0.08 -0.52 -0.06  0.27 -0.04  0.06  0.  ]
 [-0.46 -0.   -0.53  0.    0.04  0.    0.  ]
 [ 0.78  0.    0.56 -0.    0.34 -0.   -0.  ]
 [ 0.63  0.    0.83 -0.   -0.94 -0.    0.  ]
 [ 0.   -1.    0.    1.   -0.    1.    1.  ]]


In [30]:
# Note: The panda object which we have been using is an instance of the ETS class

# Calculate the world frame Jacobian using the ETS class
J0 = panda.jacob0(q)

# Calculate the end-effector frame Jacobian using the ETS class
Je = panda.jacobe(q)

# View our Jacobians
print(f"The manipulator Jacobian (world frame) is: \n{np.round(J0, 2)}")
print(f"\nThe manipulator Jacobian (end-effector frame) is: \n{np.round(Je, 2)}")

The manipulator Jacobian (world frame) is: 
[[ 0.11  0.29  0.1   0.04 -0.03 -0.01  0.  ]
 [ 0.46  0.    0.53  0.   -0.04  0.    0.  ]
 [-0.   -0.46  0.03  0.48 -0.1   0.09  0.  ]
 [-0.    0.   -0.3   0.    0.95  0.   -0.  ]
 [-0.    1.    0.   -1.    0.   -1.   -1.  ]
 [ 1.   -0.    0.96  0.   -0.32  0.    0.  ]]

The manipulator Jacobian (end-effector frame) is: 
[[ 0.07 -0.18  0.09  0.39 -0.1   0.06  0.  ]
 [-0.08 -0.52 -0.06  0.27 -0.04  0.06  0.  ]
 [-0.46 -0.   -0.53  0.    0.04  0.    0.  ]
 [ 0.78  0.    0.56 -0.    0.34 -0.    0.  ]
 [ 0.63  0.    0.83 -0.   -0.94 -0.    0.  ]
 [ 0.   -1.    0.    1.   -0.    1.    1.  ]]


In [31]:
# Number of iterations to test over
n = 1000

# Make a random matrix of q values
qt = np.random.random((n, 7))

# Slow Jacobian implementation
start = timer()
for q in qt:
    jacob0(panda, q)
slow_time = timer() - start

# Improved Jacobian implementation
start = timer()
for q in qt:
    jacob0_efficient(panda, q)
improved_time = timer() - start

# Toolbox C improved Jacobian implementation
start = timer()
for q in qt:
    panda.jacob0(q)
rtb_time = timer() - start

# Make a table
print(f"\nTiming to Calculate Manipulator Jacobian over {n} iterations\n")
table = ANSITable(
    "Function",
    "Total Time (ms)",
    "Average Time (us)",
    border="thin",
)

table.row(
    "our jacob0",
    np.round(slow_time * 1000.0, 4),
    np.round((slow_time / n) * 1000000.0, 4),
)

table.row(
    "our jacob0_efficient",
    np.round(improved_time * 1000.0, 4),
    np.round((improved_time / n) * 1000000.0, 4),
)

table.row(
    "toolbox jacob0",
    np.round(rtb_time * 1000.0, 4),
    np.round((rtb_time / n) * 1000000.0, 4),
)
table.print()


Timing to Calculate Manipulator Jacobian over 1000 iterations

┌──────────────────────┬─────────────────┬───────────────────┐
│             Function │ Total Time (ms) │ Average Time (us) │
├──────────────────────┼─────────────────┼───────────────────┤
│           our jacob0 │        653.1856 │          653.1856 │
│ our jacob0_efficient │         72.5755 │           72.5755 │
│       toolbox jacob0 │          0.5545 │            0.5545 │
└──────────────────────┴─────────────────┴───────────────────┘



In [32]:
# We will do the imports required for this notebook here

# numpy provides import array and linear algebra utilities
import numpy as np

# the robotics toolbox provides robotics specific functionality
import roboticstoolbox as rtb

# spatial math provides objects for representing transformations
import spatialmath as sm

# ansitable is a great package for printing tables in a terminal
from ansitable import ANSITable

# python mechanisms to create abstract classes
from abc import ABC, abstractmethod

# a package for creating dynamic progress bars
from progress.bar import Bar

# swift is a lightweight browser-based simulator which comes with the toolbox
from swift import Swift

# spatialgeometry is a utility package for dealing with geometric objects
import spatialgeometry as sg

# provides sleep functionaly
import time

In [52]:
import numpy as np
import roboticstoolbox as rtb
from abc import ABC, abstractmethod

class IK(ABC):
    def __init__(self, name="IK Solver", ilimit=30, slimit=100, tol=1e-30, we=np.ones(6), problems=10):
        self.name = name
        self.slimit = slimit
        self.ilimit = ilimit
        self.tol = tol
        self.We = np.diag(we)

    def solve(self, ets, Tep, q0_set):
        total_i = 0
        # Iterate through different random starting seeds (searches)
        for search in range(self.slimit):
            # q0_set should be a matrix where each row is a starting guess
            q = q0_set[search].copy()
            i = 0
            
            while i < self.ilimit:
                i += 1
                # Perform the numerical step (Newton-Raphson)
                E, q = self.step(ets, Tep, q)

                if E < self.tol:
                    return q, True, total_i + i, search + 1, E

            total_i += i
        
        return q, False, total_i, self.slimit, E

    def error(self, Te, Tep):
        # rtb.angle_axis calculates the 6-vector error (translation + orientation)
        e = rtb.angle_axis(Te, Tep)
        E = 0.5 * e @ self.We @ e
        return e, E

    @abstractmethod
    def step(self, ets, Tep, q):
        pass

class NR(IK):
    def __init__(self, pinv=False, **kwargs):
        super().__init__(**kwargs)
        self.pinv = pinv
        self.name = f"NR (pinv={pinv})"

    def step(self, ets, Tep, q):
        # Evaluate current pose
        Te = ets.eval(q)
        # Calculate error
        e, E = self.error(Te, Tep)
        # Get Jacobian in the world frame
        J = ets.jacob0(q)

        # Update joint angles: Δq = J⁺ * e
        if self.pinv:
            q += np.linalg.pinv(J) @ e
        else:
            try:
                q += np.linalg.inv(J) @ e
            except np.linalg.LinAlgError:
                # Fallback to pinv if J is singular
                q += np.linalg.pinv(J) @ e

        return E, q

In [53]:
# Setup Robot
panda = rtb.models.Panda()
ets = panda.ets()

# Setup Problems
problems = 10
slimit = 100 # Number of random restarts per problem
q_targets = ets.random_q(problems)
Tep = [ets.eval(q) for q in q_targets] # ets.eval already returns the ndarray

# Instantiate Solver
# We pass slimit here to match the number of q0 seeds available
solver = NR(pinv=True, slimit=slimit, ilimit=30, problems=problems)

# Solve each problem
for i in range(problems):
    # Generate 100 different random starting guesses for this specific problem
    q0_set = ets.random_q(slimit)
    
    q_sol, success, iterations, searches, residual = solver.solve(ets, Tep[i], q0_set)
    
    status = "SUCCESS" if success else "FAILED"
    print(f"Problem {i}: {status} | Iterations: {iterations} | Searches: {searches} | Error: {residual:.2e} ")
    # Wrap angles to [-pi, pi]
    q_wrapped = (q_sol + np.pi) % (2 * np.pi) - np.pi

    print(f"Wrapped solution: {q_wrapped}")

Problem 0: SUCCESS | Iterations: 12 | Searches: 1 | Error: 9.40e-32 
Wrapped solution: [0.19165811 0.58519152 0.03695707 0.48471264 0.62520729 2.02241708
 2.47629761]
Problem 1: SUCCESS | Iterations: 28 | Searches: 1 | Error: 8.69e-31 
Wrapped solution: [-2.23024242  1.27146525 -0.84359028 -0.11799902 -2.16172015  0.96812097
 -0.36234213]
Problem 2: SUCCESS | Iterations: 21 | Searches: 1 | Error: 6.55e-31 
Wrapped solution: [ 1.77066943  0.99696227 -1.00744179 -0.73633389 -3.1282346   2.40673986
 -0.20747985]
Problem 3: SUCCESS | Iterations: 29 | Searches: 1 | Error: 5.08e-32 
Wrapped solution: [ 2.20227047 -0.80010561 -2.05819504 -0.6261539   0.90671722  3.01312249
  2.62362596]
Problem 4: SUCCESS | Iterations: 27 | Searches: 1 | Error: 2.59e-32 
Wrapped solution: [-1.21381374  0.27931305 -2.1826693  -2.87307568 -3.06503632 -2.77403056
  0.18816161]
Problem 5: SUCCESS | Iterations: 15 | Searches: 1 | Error: 1.23e-32 
Wrapped solution: [-1.92473357 -1.22419349 -0.07201159  1.0182646   

In [54]:
import spatialmath as sm
# Setup Robot
UR5 = rtb.models.UR5()
ets = UR5.ets()

# Define a fixed target: 
# x=0.5m, y=0.2m, z=0.5m
# Orientation: Gripper pointing down (Roll=180°, Pitch=0, Yaw=0)
target_pose = sm.SE3.Rt(sm.SO3.RPY([np.pi, 0, 0]), [0.5, 0.2, 0.5])

# In your solver, Tep expects a numpy array. 
# We use .A to get the 4x4 matrix from the SE3 object.
fixed_Tep = target_pose.A 

# Now update your loop to use this fixed target for all problems
for i in range(problems):
    # We still use random restarts (q0_set) to find different joint 
    # configurations that reach the SAME fixed target.
    q0_set = ets.random_q(slimit)
    
    q_sol, success, iterations, searches, residual = solver.solve(ets, fixed_Tep, q0_set)
    
    status = "SUCCESS" if success else "FAILED"
    print(f"Problem {i}: {status} | Iterations: {iterations} | Searches: {searches} | Error: {residual:.2e}")
    
    # Wrap angles to [-pi, pi]
    q_wrapped = (q_sol + np.pi) % (2 * np.pi) - np.pi

    print(f"Wrapped solution: {q_wrapped}")

Problem 0: SUCCESS | Iterations: 9 | Searches: 1 | Error: 2.47e-32
Wrapped solution: [-2.45711195 -1.73986615 -1.66676701  0.26504082  0.88631554  3.14159223]
Problem 1: SUCCESS | Iterations: 14 | Searches: 1 | Error: 7.57e-31
Wrapped solution: [-2.45711196e+00 -1.72988548e+00 -1.19103488e+00  2.92092035e+00
 -8.86315633e-01 -4.11684908e-10]
Problem 2: SUCCESS | Iterations: 74 | Searches: 3 | Error: 9.18e-31
Wrapped solution: [-2.45711196e+00 -2.86662809e+00  1.19103485e+00  1.67559319e+00
 -8.86315633e-01  7.59026015e-08]
Problem 3: SUCCESS | Iterations: 171 | Searches: 6 | Error: 2.48e-31
Wrapped solution: [-2.45711195  2.96472782  1.66676707 -1.48990233  0.88631552 -3.1415925 ]
Problem 4: SUCCESS | Iterations: 8 | Searches: 1 | Error: 9.63e-33
Wrapped solution: [-2.45711196e+00 -1.72988548e+00 -1.19103488e+00  2.92092035e+00
 -8.86315633e-01 -8.65147953e-11]
Problem 5: SUCCESS | Iterations: 11 | Searches: 1 | Error: 6.55e-33
Wrapped solution: [ 0.20862817  0.17686484 -1.66676707 -1.